"""empty message

Revision ID: ac86a1c6bdb6
Revises: 
Create Date: 2018-08-14 04:04:01.324879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac86a1c6bdb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('number_of_conferences', sa.Integer(), nullable=True),
    sa.Column('number_of_total_teams', sa.Integer(), nullable=True),
    sa.Column('number_of_rounds', sa.Integer(), nullable=True),
    sa.Column('number_of_qualifiers', sa.Integer(), nullable=True),
    sa.Column('is_byes', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('division_name', sa.String(length=60), nullable=True),
    sa.Column('conference_name', sa.String(length=60), nullable=True),
    sa.Column('league_name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['league_name'], ['leagues.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('league_name', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['league_name'], ['leagues.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('winner', sa.String(length=200), nullable=False),
    sa.Column('loser', sa.String(length=200), nullable=False),
    sa.Column('winning_score', sa.Integer(), nullable=True),
    sa.Column('losing_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loser'], ['teams.name'], ),
    sa.ForeignKeyConstraint(['winner'], ['teams.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('leagues')
    # ### end Alembic commands ###
